const Product = require('../models/Product');
const InventoryTransaction = require('../models/InventoryTransaction');

// @desc    Get all products
// @route   GET /api/products
// @access  Public
exports.getAllProducts = async (req, res, next) => {
  try {
    const { category, minPrice, maxPrice, search } = req.query;
    let query = {};

    // Filter by category
    if (category) {
      query.Category = category;
    }

    // Filter by price range
    if (minPrice || maxPrice) {
      query.Price = {};
      if (minPrice) query.Price.$gte = parseFloat(minPrice);
      if (maxPrice) query.Price.$lte = parseFloat(maxPrice);
    }

    // Search by product name
    if (search) {
      query.ProductName = { $regex: search, $options: 'i' };
    }

    const products = await Product.find(query).sort({ CreatedAt: -1 });

    res.status(200).json({
      success: true,
      count: products.length,
      products
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get single product
// @route   GET /api/products/:id
// @access  Public
exports.getProduct = async (req, res, next) => {
  try {
    const product = await Product.findOne({ ProductID: req.params.id });

    if (!product) {
      return res.status(404).json({
        success: false,
        message: 'Product not found'
      });
    }

    res.status(200).json({
      success: true,
      product
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Create product
// @route   POST /api/products
// @access  Private (Admin only)
exports.createProduct = async (req, res, next) => {
  try {
    /**
     * ProductID is auto-generated by model
     * Client should NOT send ProductID
     */
    const product = await Product.create(req.body);

    /**
     * Log initial stock transaction
     * TransactionID auto-generated
     */
    if (product.StockQuantity > 0) {
      await InventoryTransaction.create({
        ProductID: product.ProductID,
        TransactionType: 'Stock In',
        QuantityChanged: product.StockQuantity,
        Remarks: 'Initial stock'
      });
    }

    res.status(201).json({
      success: true,
      product
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Update product
// @route   PUT /api/products/:id
// @access  Private (Admin only)
exports.updateProduct = async (req, res, next) => {
  try {
    let product = await Product.findOne({ ProductID: req.params.id });

    if (!product) {
      return res.status(404).json({
        success: false,
        message: 'Product not found'
      });
    }

    // Track stock change for inventory transaction
    const oldStock = product.StockQuantity;
    
    product = await Product.findOneAndUpdate(
      { ProductID: req.params.id },
      req.body,
      { new: true, runValidators: true }
    );

    // Log inventory transaction if stock changed
    if (req.body.StockQuantity !== undefined && req.body.StockQuantity !== oldStock) {
      const quantityChanged = req.body.StockQuantity - oldStock;
      await InventoryTransaction.create({
        ProductID: product.ProductID,
        TransactionType: quantityChanged > 0 ? 'Stock In' : 'Stock Out',
        QuantityChanged: Math.abs(quantityChanged),
        Remarks: 'Stock adjustment via product update'
      });
    }

    res.status(200).json({
      success: true,
      product
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Delete product
// @route   DELETE /api/products/:id
// @access  Private (Admin only)
exports.deleteProduct = async (req, res, next) => {
  try {
    const product = await Product.findOne({ ProductID: req.params.id });

    if (!product) {
      return res.status(404).json({
        success: false,
        message: 'Product not found'
      });
    }

    await product.deleteOne();

    res.status(200).json({
      success: true,
      message: 'Product deleted successfully'
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get low stock products
// @route   GET /api/products/low-stock/:threshold
// @access  Private (Admin/Staff)
exports.getLowStockProducts = async (req, res, next) => {
  try {
    const threshold = parseInt(req.params.threshold) || 10;
    
    const products = await Product.find({
      StockQuantity: { $lte: threshold }
    }).sort({ StockQuantity: 1 });

    res.status(200).json({
      success: true,
      count: products.length,
      products
    });
  } catch (error) {
    next(error);
  }
};